inherit_gem:
  rubocop-rails-omakase: rubocop.yml

require:
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - "db/schema.rb"
    - "bin/*"
    - "node_modules/**/*"
    - "config/initializers/devise.rb"
    - "config/routes.rb"
    - "db/migrate/*"

Layout/LineLength:
  Max: 120

RSpec:
  Enabled: true

RSpecRails:
  Enabled: true

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/ExampleLength:
  Max: 25

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 5

