# Omakase Ruby styling for Rails
inherit_gem:
  rubocop-rails-omakase: rubocop.yml

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  Exclude:
    - "db/schema.rb"
    - "bin/*"
    - "node_modules/**/*"
    - 'config/initializers/devise.rb'
    - 'config/routes.rb'
    - 'db/migrate/*'

Layout/LineLength:
  Max: 120
